Service worker configuration options in jupyter-lite.json
jupyterlite/jupyterlite pull request #737
Opened 2022-07-13 15:05 UTC by joemarshall

I added a couple of options to the serviceworker plugin, to allow you to 

a) Point it at somewhere else in the case that you want to host jupyterlite files in a subfolder of your site, but want the service worker to be able to handle things at that level.
b) Disable the service worker (deleting the services.js script isn't enough, because if you use your own service worker, jupyterlite clobbers it every time you load the page, even if the script is missing)

2022-07-25 08:29 UTC, martinRenou approved these changes
Thanks!

2022-08-03 12:52 UTC, joemarshall commented
Any chance this could be merged into main ready for the next release, so I can drop my patches from the build?

2022-08-03 13:12 UTC, martinRenou requested changes
Sorry, my previous review was from the phone I missed something

2022-08-03 13:12 UTC, martinRenou commented on packages/server/src/serviceworker.ts
> +
This code has been duplicated (it's already just below)

```suggestion
```

2022-08-05 06:43 UTC, jtpio commented on packages/server/src/serviceworker.ts
> +    if (this._config['disabled']) {
Normally the following notation is preferred when the object is properly typed:

```suggestion
    if (this._config.disabled) {
```

2022-08-05 06:45 UTC, jtpio commented
>  Disable the service worker (deleting the services.js script isn't enough, because if you use your own service worker, jupyterlite clobbers it every time you load the page, even if the script is missing)

@joemarshall curious if you tried using the plugin system to swap the default plugin with your own?

Thinking that as an alternative to adding a config option like in this PR, maybe it's possible to add `@jupyterlite/server-extension:service-worker` to `disabledExtensions` so the plugin is disabled. Then you can provide your own plugin with full control on it.

2022-08-16 10:02 UTC, echarles commented
@joemarshall I was looking for that feature, actually not only for the `'services.js` loading but also for the resources loaded by the Pyolite (python) kernel. The needed resources (all.json...) are for now expected to be served under the `build/pypi` folder of the generated jupyterlite website. 

https://github.com/jupyterlite/jupyterlite/blob/dac5a8202e25c713cf653454025c832c5b7b0a2d/packages/pyolite-kernel/src/kernel.ts#L61

At some point, those resources have the same requirements as the `services.js`, served by another separated server under a configurable URL.

Have you though expanding this PR to that case (anyway worth thinking about that while adding more configuration).

2022-08-17 07:51 UTC, jtpio commented
> are for now expected to be served under the `build/pypi` folder of the generated jupyterlite website.

Right. This will likely be fixed when the Pyodide kernel is moved outside of the main repository: https://github.com/jupyterlite/jupyterlite/issues/386

2022-12-22 13:33 UTC, jtpio commented
@joemarshall just checking if this PR is still valid?

There have been a few iterations on the service worker lately which should allow for more flexibility:

- https://github.com/jupyterlite/jupyterlite/pull/839
- https://github.com/jupyterlite/jupyterlite/pull/899

2023-01-01 22:30 UTC, joemarshall commented
I think probably you can close this, at least for my purposes - I ended up requiring site isolation for the streaming code in pyodide-http, because if you can isolate, that is much cleaner, and if you don't have server access to isolate the site, you can isolate using a service worker anyway.

It'll all be a moot point once the Webassembly/promise integration proposal is no longer behind experimental flags in browsers, because no one will need serviceworkers for handling io any more, so they can just stick to being for caching as they are designed for.

2023-03-14 08:12 UTC, jtpio commented
> I think probably you can close this

Alright thanks @joemarshall for getting back and for investigating this :+1:

2023-03-14 08:12 UTC, closed without merging